export const API_ERROR_CODES = {
  FORBIDDEN: "FORBIDDEN",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  INVALID_API_KEY: "INVALID_API_KEY",
  LINK_LIMIT_REACHED: "LINK_LIMIT_REACHED",
  NOT_FOUND: "NOT_FOUND",
  PATH_ALREADY_IN_USE: "PATH_ALREADY_IN_USE",
  PRO_REQUIRED: "PRO_REQUIRED",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  SHORT_LINK_LIMIT_REACHED: "SHORT_LINK_LIMIT_REACHED",
  UNAUTHORIZED: "UNAUTHORIZED",
  UNSAFE_URL: "UNSAFE_URL",
  URL_UNREACHABLE: "URL_UNREACHABLE",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  WEBHOOK_LIMIT_REACHED: "WEBHOOK_LIMIT_REACHED",
} as const;

export type ApiErrorCode = (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES];
