/**
 * Explicit icon component imports for the icon registry.
 * Separated from icon-registry.ts to keep metadata tree-shakeable from components.
 */

import {
  SiApple,
  SiApplepodcasts,
  SiBehance,
  SiBitcoin,
  SiBluesky,
  SiBuymeacoffee,
  SiCashapp,
  SiDiscord,
  SiDribbble,
  SiDropbox,
  SiEtsy,
  SiFacebook,
  SiFigma,
  SiGithub,
  SiGitlab,
  SiGoogle,
  SiGoogledrive,
  SiInstagram,
  SiKick,
  SiKofi,
  SiLightning,
  SiLinktree,
  SiMastodon,
  SiMedium,
  SiNotion,
  SiOnlyfans,
  SiPatreon,
  SiPaypal,
  SiPinterest,
  SiProducthunt,
  SiReddit,
  SiSignal,
  SiSnapchat,
  SiSoundcloud,
  SiSpotify,
  SiSteam,
  SiStripe,
  SiSubstack,
  SiTelegram,
  SiThreads,
  SiTiktok,
  SiTumblr,
  SiTwitch,
  SiVenmo,
  SiVimeo,
  SiWhatsapp,
  SiX,
  SiYoutube,
} from "@icons-pack/react-simple-icons";
import {
  Anchor,
  AtSign,
  Award,
  BadgeCheck,
  Banknote,
  Bike,
  Bolt,
  BookOpen,
  Bookmark,
  Briefcase,
  Brush,
  Cake,
  Calendar,
  Camera,
  Clock,
  Code,
  Coffee,
  Cpu,
  Crown,
  Download,
  Dumbbell,
  Earth,
  Flame,
  Gamepad2,
  Gift,
  GraduationCap,
  Guitar,
  Headphones,
  Heart,
  House,
  Image,
  Inbox,
  Key,
  Landmark,
  Layers,
  Lightbulb,
  Link2,
  Lock,
  Mail,
  MapPin,
  Megaphone,
  Mic,
  Monitor,
  Music,
  Newspaper,
  Palette,
  PenTool,
  Phone,
  Plane,
  Podcast,
  Rocket,
  Rss,
  Scissors,
  Shield,
  ShoppingBag,
  ShoppingCart,
  Sparkles,
  Star,
  Store,
  Terminal,
  Ticket,
  Trophy,
  Tv,
  Umbrella,
  User,
  Utensils,
  Video,
  Wallet,
  WandSparkles,
  Wrench,
  Zap,
} from "lucide-react";
import type * as React from "react";

type IconComponent = React.ComponentType<{ className?: string; color?: string }>;

/** Simple Icons component map. Keys match the name portion of `si:name` IDs. */
export const SI_ICON_COMPONENTS: Record<string, IconComponent> = {
  apple: SiApple,
  applepodcasts: SiApplepodcasts,
  behance: SiBehance,
  bitcoin: SiBitcoin,
  bluesky: SiBluesky,
  buymeacoffee: SiBuymeacoffee,
  cashapp: SiCashapp,
  discord: SiDiscord,
  dribbble: SiDribbble,
  dropbox: SiDropbox,
  etsy: SiEtsy,
  facebook: SiFacebook,
  figma: SiFigma,
  github: SiGithub,
  gitlab: SiGitlab,
  google: SiGoogle,
  googledrive: SiGoogledrive,
  instagram: SiInstagram,
  kick: SiKick,
  kofi: SiKofi,
  lightning: SiLightning,
  linktree: SiLinktree,
  mastodon: SiMastodon,
  medium: SiMedium,
  notion: SiNotion,
  onlyfans: SiOnlyfans,
  patreon: SiPatreon,
  paypal: SiPaypal,
  pinterest: SiPinterest,
  producthunt: SiProducthunt,
  reddit: SiReddit,
  signal: SiSignal,
  snapchat: SiSnapchat,
  soundcloud: SiSoundcloud,
  spotify: SiSpotify,
  steam: SiSteam,
  stripe: SiStripe,
  substack: SiSubstack,
  telegram: SiTelegram,
  threads: SiThreads,
  tiktok: SiTiktok,
  tumblr: SiTumblr,
  twitch: SiTwitch,
  venmo: SiVenmo,
  vimeo: SiVimeo,
  whatsapp: SiWhatsapp,
  x: SiX,
  youtube: SiYoutube,
};

/** Lucide icon component map. Keys match the name portion of `lucide:name` IDs. */
export const LUCIDE_ICON_COMPONENTS: Record<string, IconComponent> = {
  anchor: Anchor,
  "at-sign": AtSign,
  award: Award,
  "badge-check": BadgeCheck,
  banknote: Banknote,
  bike: Bike,
  bolt: Bolt,
  "book-open": BookOpen,
  bookmark: Bookmark,
  briefcase: Briefcase,
  brush: Brush,
  cake: Cake,
  calendar: Calendar,
  camera: Camera,
  clock: Clock,
  code: Code,
  coffee: Coffee,
  cpu: Cpu,
  crown: Crown,
  download: Download,
  dumbbell: Dumbbell,
  earth: Earth,
  flame: Flame,
  "gamepad-2": Gamepad2,
  gift: Gift,
  "graduation-cap": GraduationCap,
  guitar: Guitar,
  headphones: Headphones,
  heart: Heart,
  house: House,
  image: Image,
  inbox: Inbox,
  key: Key,
  landmark: Landmark,
  layers: Layers,
  lightbulb: Lightbulb,
  "link-2": Link2,
  lock: Lock,
  mail: Mail,
  "map-pin": MapPin,
  megaphone: Megaphone,
  mic: Mic,
  monitor: Monitor,
  music: Music,
  newspaper: Newspaper,
  palette: Palette,
  "pen-tool": PenTool,
  phone: Phone,
  plane: Plane,
  podcast: Podcast,
  rocket: Rocket,
  rss: Rss,
  scissors: Scissors,
  shield: Shield,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  sparkles: Sparkles,
  star: Star,
  store: Store,
  terminal: Terminal,
  ticket: Ticket,
  trophy: Trophy,
  tv: Tv,
  umbrella: Umbrella,
  user: User,
  utensils: Utensils,
  video: Video,
  wallet: Wallet,
  "wand-sparkles": WandSparkles,
  wrench: Wrench,
  zap: Zap,
};
